// crates/amos-tauri/frontend-ts/src/components/HomeDock.tsx
import { useEffect, useRef, useState, type DragEvent, type TouchEvent as ReactTouchEvent } from "react";
import type { HomeLayout } from "../lib/amosStore";
import { appIcon, appTitleKey } from "../apps";
import { AppIconTile } from "./AppIcon";
import { useI18n } from "../i18n";
import { zh, type MessageKey } from "../i18n/locales/zh";
import { NOTIF_KEY, SETTINGS_KEY, countForApp, dndActive, normalizeQuick, type Notif } from "../lib/settings";
import { useStoreValue } from "../lib/useStoreValue";
import { iconSvg } from "../lib/sysIcons";
import { HomeWidgets } from "./HomeWidgets";
import type { StoreTile } from "../lib/storeApps";
import { amosLog, amosWarn } from "../lib/debugLog";

/** Fine-pointer (mouse/trackpad) → allow HTML5 drag-to-reorder. Coarse/touch →
 *  disable native drag so a horizontal swipe pages the dock instead of dragging.
 *  Falls back to draggable when matchMedia is unavailable (SSR / happy-dom tests). */
function finePointerEnabled(): boolean {
  if (typeof window === "undefined" || !window.matchMedia) return true;
  return window.matchMedia("(pointer: fine)").matches;
}

function IconTile({
  id,
  icon,
  label,
  unread,
  pulse,
  reorderable,
  onClick,
  onDragStart,
  onDragOver,
  onDrop,
}: {
  id: string;
  icon: string;
  label: string;
  unread: number;
  /** Brief "launch" highlight when the user picks this app from search. */
  pulse?: boolean;
  /** HTML5 drag-to-reorder is a fine-pointer (mouse) affordance; touch devices
   *  keep icons non-draggable so a horizontal swipe pages the dock instead of
   *  starting a native drag that swallows the touch. */
  reorderable: boolean;
  onClick: () => void;
  onDragStart: (id: string) => void;
  onDragOver: (e: DragEvent) => void;
  onDrop: (id: string) => void;
}) {
  return (
    <button
      aria-label={label}
      title={label}
      draggable={reorderable}
      onClick={onClick}
      onDragStart={reorderable ? (e) => {
        onDragStart(id);
        e.dataTransfer?.setData("text/plain", id);
      } : undefined}
      onDragOver={(e) => onDragOver(e)}
      onDrop={(e) => {
        e.preventDefault();
        onDrop(id);
      }}
      className="group flex w-16 flex-col items-center gap-1 outline-none"
    >
      <span className="relative">
        <AppIconTile
          id={id}
          icon={icon}
          tileClassName={
            "h-14 w-14 rounded-[19px] group-hover:-translate-y-0.5 group-active:scale-90" +
            (pulse ? " animate-pulse ring-2 ring-accent" : "")
          }
          glyphClassName="text-[2.5rem]"
        />
        {unread > 0 && (
          <span className="absolute -right-1 -top-1 grid min-w-[18px] place-items-center rounded-full bg-danger px-1 text-[11px] font-bold text-white ring-2 ring-white dark:ring-neutral-900">
            {unread > 99 ? "99+" : unread}
          </span>
        )}
      </span>
      <span className="max-w-full truncate text-xs font-medium text-neutral-800 transition-colors group-hover:text-accent dark:text-neutral-200">{label}</span>
    </button>
  );
}

export default function HomeDock({
  layout,
  onOpen,
  onMove,
  onSearch,
  onLibrary,
  pulseId,
  ext = [],
}: {
  layout: HomeLayout;
  onOpen: (id: string) => void;
  /** (dragId, overId) after a drop — parent persists with saveLayout. */
  onMove: (dragId: string, overId: string) => void;
  /** Open Spotlight search (shown as a discreet search pill at the bottom of the grid). */
  onSearch?: () => void;
  /** Enter the iOS-style "App Library" page (trailing page / pager dot). */
  onLibrary?: () => void;
  /** Icon to briefly highlight (id) after a soft-launch from search. */
  pulseId?: string | null;
  /** Store-installed (third-party) tiles to render alongside built-ins. */
  ext?: StoreTile[];
}) {
  const { t } = useI18n();
  // Reactive reads: home unread badges (and their DND suppression) update live
  // as notifications / quick-settings change (same window or cross-window).
  const notifs = useStoreValue<Notif[]>(NOTIF_KEY, []);
  const quiet = dndActive(normalizeQuick(useStoreValue<unknown>(SETTINGS_KEY, {})));
  const dragId = useRef<string | null>(null);
  const reorderable = useRef(finePointerEnabled()).current;

  const extById = new Map(ext.map((e) => [e.id, e]));
  const extName = (id: string): string | undefined => extById.get(id)?.name;

  const labelOf = (id: string): string => {
    const key = appTitleKey(id);
    return key ? t(key) : extName(id) ?? id;
  };
  const known = (id: string): boolean => appTitleKey(id) !== null || extById.has(id);
  const zhName = (id: string): string => {
    const key = appTitleKey(id) as MessageKey | null;
    return key ? zh[key] : extName(id) ?? id;
  };
  const unreadOf = (id: string) =>
    quiet || extById.has(id) ? 0 : countForApp(notifs, zhName(id));
  const iconOf = (id: string): string => extById.get(id)?.icon ?? appIcon(id);
  const handleStart = (id: string) => {
    dragId.current = id;
  };
  const handleDragOver = (e: DragEvent) => e.preventDefault();
  const handleDrop = (id: string) => {
    const src = dragId.current;
    dragId.current = null;
    if (src && src !== id) onMove(src, id);
  };
  const openTap = (id: string) => {
    if (dragId.current) {
      dragId.current = null; // a tap right after a drag shouldn't open the app
      return;
    }
    onOpen(id);
  };

  const renderIcon = (id: string) => (
    <IconTile
      key={id}
      id={id}
      icon={iconOf(id)}
      label={labelOf(id)}
      unread={unreadOf(id)}
      pulse={pulseId === id}
      reorderable={reorderable}
      onClick={() => openTap(id)}
      onDragStart={handleStart}
      onDragOver={handleDragOver}
      onDrop={handleDrop}
    />
  );

  const pageIds = layout.page.filter(known);
  const dockIds = layout.dock.filter(known);

  // ---- Main icon grid: horizontal multi-page ----
  // The home's app icons live on horizontal pages (swipe left/right to page).
  // HomeWidgets stay fixed above; the bottom dock bar stays a single row below.
  const GRID_COLS = 4;
  const GRID_ROWS = 3;
  const GRID_PER_PAGE = GRID_COLS * GRID_ROWS; // 12 icons per page
  const gridPages: string[][] = [];
  for (let i = 0; i < pageIds.length; i += GRID_PER_PAGE) {
    gridPages.push(pageIds.slice(i, i + GRID_PER_PAGE));
  }
  const [gridPage, setGridPage] = useState(0);
  useEffect(() => {
    if (gridPage > Math.max(0, gridPages.length - 1)) {
      setGridPage(Math.max(0, gridPages.length - 1));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gridPages.length]);
  const shownGrid = gridPages.length ? (gridPages[Math.min(gridPage, gridPages.length - 1)] ?? []) : [];
  const gridPanX = useRef<number | null>(null);
  const gridPanned = useRef(false);
  const onGridStart = (e: ReactTouchEvent<HTMLDivElement>) => {
    const x = e.touches[0]?.clientX;
    gridPanX.current = x == null ? null : x;
    gridPanned.current = false;
  };
  const onGridMove = (e: ReactTouchEvent<HTMLDivElement>) => {
    const x0 = gridPanX.current;
    if (x0 == null || gridPanned.current) return;
    const x = e.touches[0]?.clientX;
    if (x == null) return;
    const dx = x - x0;
    if (Math.abs(dx) < 48) return;
    gridPanned.current = true;
    gridPanX.current = null;
    dragId.current = "__grid_pan__";
    window.setTimeout(() => {
      if (dragId.current === "__grid_pan__") dragId.current = null;
    }, 300);
    if (gridPages.length <= 1) {
      // A single page has nowhere to page to — a swipe to the left is the iOS
      // "keep going past the last page" gesture that opens the App Library.
      if (dx < 0) onLibrary?.();
    } else if (gridPage >= gridPages.length - 1 && dx < 0) {
      // Past the last icon page → the trailing "App Library" page.
      onLibrary?.();
    } else if (dx < 0) {
      setGridPage((p) => Math.min(p + 1, gridPages.length - 1));
    } else {
      setGridPage((p) => Math.max(p - 1, 0));
    }
  };
  const onGridEnd = () => {
    gridPanX.current = null;
  };

  // ---- on-device diagnosis for "dock not rendering" ----
  const reported = useRef(false);
  const lastEmpty = useRef<boolean | null>(null);
  useEffect(() => {
    reported.current = false;
    lastEmpty.current = null;
  }, [layout]);
  if (!reported.current) {
    reported.current = true;
    amosLog("dock", "mounted", { gridPages: gridPages.length, pageIds, dockIds });
  }
  const emptyNow = dockIds.length === 0;
  if (emptyNow !== lastEmpty.current) {
    lastEmpty.current = emptyNow;
    if (emptyNow) {
      const dropped = layout.dock.filter((id) => !known(id));
      amosWarn("dock", "dock icon list is empty", { persistedDock: layout.dock, droppedUnknown: dropped });
    }
  }

  return (
    <div className="flex h-full flex-col px-4 pb-3">
      {/* main paged region: a horizontal swipe ANYWHERE in this column (incl. over
          the clock/weather widgets) pages the icon grid, iOS-home style. */}
      <div
        className="flex min-h-0 flex-1 flex-col overflow-hidden"
        style={{ touchAction: "pan-y" }}
        onTouchStart={onGridStart}
        onTouchMove={onGridMove}
        onTouchEnd={onGridEnd}
        onTouchCancel={onGridEnd}
      >
        {/* fixed widgets header — generous breathing room below the status bar */}
        <div className="shrink-0 px-1 pt-[48px]">
          <HomeWidgets onOpen={onOpen} />
        </div>

        <div className="flex min-h-0 flex-1 flex-col justify-center">
          <div className="grid grid-cols-4 place-content-center gap-y-5" data-testid="home-grid">
            {shownGrid.map(renderIcon)}
          </div>
        </div>
        <div className="mt-1 flex items-center justify-center gap-1">
          {gridPages.length > 1 && (
            <div data-testid="home-dots" className="flex items-center justify-center gap-0.5">
              {gridPages.map((_, i) => {
                const active = i === Math.min(gridPage, gridPages.length - 1);
                return (
                  <button
                    key={i}
                    type="button"
                    data-testid="home-dot"
                    aria-label={`page ${i + 1} of ${gridPages.length}`}
                    aria-current={active ? "true" : undefined}
                    onClick={() => setGridPage(Math.min(i, gridPages.length - 1))}
                    className="grid h-5 min-w-5 cursor-pointer place-items-center transition active:scale-90"
                  >
                    <span
                      aria-hidden
                      className={
                        "block rounded-full transition-all " +
                        (active
                          ? "h-1.5 w-3.5 bg-neutral-500/80 dark:bg-neutral-300/80"
                          : "h-1.5 w-1.5 bg-neutral-400/40 dark:bg-neutral-600/60")
                      }
                    />
                  </button>
                );
              })}
            </div>
          )}
          {/* iOS-style "App Library" trailing-page entry (always present, even with a
              single icon page). A bigger 4×4 mini-app-grid icon, like the iOS App
              Library indicator. Left-swipe past the last page reaches the same place. */}
          <button
            type="button"
            data-testid="app-library-entry"
            aria-label={t("appLibrary.title")}
            title={t("appLibrary.title")}
            onClick={onLibrary}
            className="ml-1 grid h-6 w-6 cursor-pointer place-items-center rounded-[7px] bg-white/45 shadow-sm ring-1 ring-black/5 transition hover:scale-105 active:scale-90 dark:bg-white/10 dark:ring-white/10"
          >
            <span aria-hidden className="grid w-4 grid-cols-4 gap-px">
              {Array.from({ length: 16 }).map((_, i) => (
                <span
                  key={i}
                  className="h-[3px] w-[3px] rounded-[0.5px] bg-neutral-600/70 dark:bg-neutral-300/70"
                />
              ))}
            </span>
          </button>
        </div>
      </div>

      {onSearch && (
        <button
          type="button"
          aria-label="search"
          onClick={onSearch}
          className="mx-auto mb-1.5 flex h-8 cursor-pointer items-center justify-center gap-1 rounded-full bg-white/45 px-3 text-xs font-medium text-neutral-700 shadow-sm ring-1 ring-black/5 transition active:scale-90 dark:bg-white/10 dark:text-neutral-200 dark:ring-white/10"
        >
          <span data-icon="search" dangerouslySetInnerHTML={{ __html: iconSvg("search", "h-3.5 w-3.5") }} /> <span>{t("home.search")}</span>
        </button>
      )}

      {/* bottom dock bar: single fixed row (no paging) */}
      <div className="dock-mag flex items-end justify-around rounded-3xl bg-white/30 px-2 py-3 shadow-inner ring-1 ring-black/5 backdrop-blur-md dark:bg-neutral-900/40 dark:ring-white/10">
        {dockIds.map(renderIcon)}
      </div>
    </div>
  );
}

// crates/amos-tauri/frontend-ts/src/svelte/HomeDock.svelte
<script lang="ts">
  // HomeDock.svelte — Svelte 5 (runes) port of the React `HomeDock` (the home
  // screen: widgets + paged icon grid + single-row bottom dock bar).
  //
  // It is a CONTROLLED leaf: the React shell owns navigation + the home layout,
  // and pushes { layout, ext, pulseId } down reactively through the shared
  // propsBus channel "home" (in-place, no remount → the icon-grid page index is
  // preserved across reorders). One-shot actions (open / move / search) go back
  // up over the same channel.
  //
  // Pure logic is REUSED, not rewritten: model helpers from lib/settings,
  // i18n from locale.svelte.ts, notifications/DND reactively via createStoreValue
  // (svelte/store) — the twin of React's useStoreValue.
  import { t, locale } from "./locale.svelte";
  import { homeDownToSpotlight } from "../lib/edgeSwipe";
  import { onMount } from "svelte";
  import { appIcon, appTitleKey } from "../lib/appMeta";
  import type { HomeLayout } from "../lib/amosStore";
  import {
    NOTIF_KEY,
    SETTINGS_KEY,
    countForApp,
    dndActive,
    normalizeQuick,
    type Notif,
  } from "../lib/settings";
  import { createStoreValue } from "./store";
  import type { StoreTile } from "../lib/storeApps";
  import { propsChannel } from "./propsBus";
  import AppIcon from "./AppIcon.svelte";
  import { fmtClock } from "../lib/time";
  import { forecast } from "../lib/weather";
  import { zh, type MessageKey } from "../i18n/locales/zh";
  import { amosLog, amosWarn } from "../lib/debugLog";

  interface HomeProps {
    layout: HomeLayout;
    ext: StoreTile[];
    pulseId: string | null;
  }
  const home = propsChannel<HomeProps>("home");

  // ---- External props (host pushes in place; never remounts) ----
  let incoming = $state<HomeProps | null>(null);
  $effect(() => {
    const un = home.subscribe((v) => {
      if (v !== undefined) incoming = v;
    });
    return un;
  });

  const EMPTY_LAYOUT: HomeLayout = { page: [], dock: [], hidden: [] };
  const layout = $derived(incoming?.layout ?? EMPTY_LAYOUT);
  const ext = $derived(incoming?.ext ?? []);
  const pulseId = $derived(incoming?.pulseId ?? null);

  // ---- Reactive notifications + Do-Not-Disturb (live, cross-window) ----
  const notifStore = createStoreValue<Notif[]>(NOTIF_KEY, []);
  const quickStore = createStoreValue<unknown>(SETTINGS_KEY, {});
  let notifs = $state<Notif[]>([]);
  let quick = $state<unknown>({});
  $effect(() => {
    const un = notifStore.subscribe((v) => (notifs = v));
    return un;
  });
  $effect(() => {
    const un = quickStore.subscribe((v) => (quick = v));
    return un;
  });
  const quiet = $derived(dndActive(normalizeQuick(quick)));

  // Fine-pointer (mouse) → allow drag-to-reorder; coarse/touch disables native
  // drag so a horizontal swipe pages the grid instead. Fall back to draggable
  // when matchMedia is absent (SSR / happy-dom).
  const reorderable = (() => {
    try {
      return (
        typeof window === "undefined" ||
        !window.matchMedia ||
        window.matchMedia("(pointer: fine)").matches
      );
    } catch {
      return true;
    }
  })();

  // ---- label / badge / icon resolution (pure lib reuse) ----
  const extById = $derived(new Map(ext.map((e) => [e.id, e])));
  const extName = (id: string): string | undefined => extById.get(id)?.name;
  const known = (id: string): boolean => appTitleKey(id) !== null || extById.has(id);
  const zhName = (id: string): string => {
    const key = appTitleKey(id) as MessageKey | null;
    return key ? zh[key] : (extName(id) ?? id);
  };
  const labelOf = (id: string): string => {
    const key = appTitleKey(id);
    return key ? t(key) : (extName(id) ?? id);
  };
  const iconOf = (id: string): string => extById.get(id)?.icon ?? appIcon(id);
  const unreadOf = (id: string): number =>
    quiet || extById.has(id) ? 0 : countForApp(notifs, zhName(id));


  // ---- Main icon grid: horizontal multi-page (widgets fixed; dock single row) ----
  const pageIds = $derived(layout.page.filter(known));
  const dockIds = $derived(layout.dock.filter(known));

  function buildPages(ids: string[]): string[][] {
    const pages: string[][] = [];
    const per = 12; // 4 cols x 3 rows
    for (let i = 0; i < ids.length; i += per) pages.push(ids.slice(i, i + per));
    return pages;
  }
  const gridPages = $derived(buildPages(pageIds));
  let gridPage = $state(0);
  const lastIndex = $derived(Math.max(0, gridPages.length - 1));
  const safePage = $derived(gridPage > lastIndex ? lastIndex : gridPage);
  const shownGrid = $derived(gridPages[safePage] ?? []);
  // Clamp the stored page index when the grid shrinks (parity with the React
  // `useEffect` clamp): a stale high index must not auto-jump back to a later
  // page if the grid is later expanded again.
  $effect(() => {
    if (gridPage > lastIndex) gridPage = lastIndex;
  });

  // Transient gesture state (non-reactive mirrors of the React refs).
  let dragId: string | null = null;
  let panX: number | null = null;
  let panned = false;

  function handleDragStart(id: string): void {
    dragId = id;
  }
  function handleDrop(id: string): void {
    const src = dragId;
    dragId = null;
    if (src && src !== id) home.emit("move", { drag: src, over: id });
  }
  function handleTap(id: string): void {
    if (dragId) {
      dragId = null; // a tap right after a drag shouldn't open the app
      return;
    }
    home.emit("open", id);
  }
  function onGridStart(e: TouchEvent): void {
    const x = e.touches[0]?.clientX;
    panX = x == null ? null : x;
    panned = false;
  }
  function onGridMove(e: TouchEvent): void {
    const x0 = panX;
    if (x0 == null || panned) return;
    const x = e.touches[0]?.clientX;
    if (x == null) return;
    const dx = x - x0;
    if (Math.abs(dx) < 48) return;
    panned = true;
    panX = null;
    dragId = "__grid_pan__";
    window.setTimeout(() => {
      if (dragId === "__grid_pan__") dragId = null;
    }, 300);
    if (gridPages.length <= 1) {
      // A single page has nowhere to page to — a swipe to the left is the iOS
      // "keep going past the last page" gesture that opens the App Library.
      if (dx < 0) home.emit("library");
    } else if (gridPage >= gridPages.length - 1 && dx < 0) {
      // Past the last icon page → the trailing "App Library" page.
      home.emit("library");
    } else if (dx < 0) {
      gridPage = Math.min(gridPage + 1, gridPages.length - 1);
    } else {
      gridPage = Math.max(gridPage - 1, 0);
    }
  }
  function onGridEnd(): void {
    panX = null;
  }

  // ---- Home-body downward swipe → Spotlight (iPhone "swipe down on Home to
  // search"). The top status edge is reserved for the Notification Center, and
  // the bottom zone for the dock / Recents — see lib/edgeSwipe.ts. The gesture is
  // *vertically dominant* (down travel > |horizontal travel|) so an intentional
  // left/right page-swipe on the icon grid never also opens Spotlight.
  let swipeX: number | null = null;
  let swipeY: number | null = null;
  function onHomeTouchStart(e: TouchEvent): void {
    const t = e.touches[0];
    swipeX = t == null ? null : t.clientX;
    swipeY = t == null ? null : t.clientY;
  }
  function onHomeTouchEnd(e: TouchEvent): void {
    const x0 = swipeX;
    const y0 = swipeY;
    swipeX = null;
    swipeY = null;
    if (x0 == null || y0 == null) return;
    const t = e.changedTouches[0];
    if (t == null) return;
    const dy = t.clientY - y0;
    const dx = Math.abs(t.clientX - x0);
    // Vertically dominant downward swipe within the home body → Spotlight.
    if (dy > dx && homeDownToSpotlight(y0, t.clientY, window.innerHeight)) home.emit("search");
  }
  // A system/touch-cancel interrupts the gesture → never open Spotlight, just reset.
  function onHomeTouchCancel(): void {
    swipeX = null;
    swipeY = null;
  }

  // ---- on-device diagnosis for "dock not rendering" (parity with React) ----
  onMount(() => {
    amosLog("dock", "mounted", { gridPages: gridPages.length, pageIds, dockIds });
  });
  let lastEmpty: boolean | null = null;
  const emptyNow = $derived(dockIds.length === 0);
  $effect(() => {
    if (emptyNow && emptyNow !== lastEmpty) {
      amosWarn("dock", "dock icon list is empty", { dockIds });
    }
    lastEmpty = emptyNow;
  });

  // ---- widgets (clock + weather, live clock) ----
  let now = $state(new Date());
  $effect(() => {
    const id = setInterval(() => (now = new Date()), 1000);
    return () => clearInterval(id);
  });
  const today = $derived(forecast()[0]);
  const dateStr = $derived(
    new Intl.DateTimeFormat(locale() === "zh" ? "zh-CN" : "en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
    }).format(now),
  );
</script>


<div
  class="flex h-full flex-col px-4 pb-3"
  role="group"
  aria-label="home screen"
  style="touch-action: none"
  ontouchstart={onHomeTouchStart}
  ontouchend={onHomeTouchEnd}
  ontouchcancel={onHomeTouchCancel}
>
  <!-- main paged region: a horizontal swipe ANYWHERE in this column pages the
       icon grid; widgets stay fixed above, bottom dock stays a single row below -->
  <div
    class="flex min-h-0 flex-1 flex-col overflow-hidden"
    role="group"
    aria-label="home pages"
    style="touch-action: pan-y"
    ontouchstart={onGridStart}
    ontouchmove={onGridMove}
    ontouchend={onGridEnd}
    ontouchcancel={onGridEnd}
  >
    <!-- fixed widgets header -->
    <div class="shrink-0 px-1 pt-[48px]">
      <div class="grid grid-cols-[1fr_auto] gap-3">
        <button
          class="flex flex-col justify-center rounded-3xl bg-white/40 p-4 text-left shadow-sm ring-1 ring-black/5 backdrop-blur-md transition active:scale-95 dark:bg-white/10 dark:ring-white/10"
          onclick={() => home.emit("open", "clock")}
        >
          <div class="text-4xl font-thin leading-none tabular-nums">{fmtClock(now)}</div>
          <div class="mt-2 text-xs opacity-70">{dateStr}</div>
        </button>
{#if today}
          <button
            class="flex flex-col items-center justify-center rounded-3xl bg-white/40 p-4 px-5 text-left shadow-sm ring-1 ring-black/5 backdrop-blur-md transition active:scale-95 dark:bg-white/10 dark:ring-white/10"
            aria-label={t("app.weather")}
            onclick={() => home.emit("open", "weather")}
          >
            <div class="text-2xl">{today.icon}</div>
            <div class="text-xl font-thin tabular-nums">{today.temp}°</div>
            <div class="text-[10px] opacity-70">{t("weather.today")}</div>
          </button>
        {/if}
      </div>
    </div>

    <!-- paged icon grid -->
    <div class="flex min-h-0 flex-1 flex-col justify-center">
      <div class="grid grid-cols-4 place-content-center gap-y-5" data-testid="home-grid">
        {#each shownGrid as id (id)}
          {@render tile(id)}
        {/each}
      </div>
    </div>
    <div class="mt-1 flex items-center justify-center gap-1">
      {#if gridPages.length > 1}
        <div data-testid="home-dots" class="flex items-center justify-center gap-0.5">
          {#each gridPages as _, i (i)}
            <button
              type="button"
              data-testid="home-dot"
              aria-label={`page ${i + 1} of ${gridPages.length}`}
              aria-current={i === safePage ? "true" : undefined}
              onclick={() => (gridPage = Math.min(i, lastIndex))}
              class="grid h-5 min-w-5 cursor-pointer place-items-center transition active:scale-90"
            >
              <span
                aria-hidden="true"
                class={
                  "block rounded-full transition-all " +
                  (i === safePage
                    ? "h-1.5 w-3.5 bg-neutral-500/80 dark:bg-neutral-300/80"
                    : "h-1.5 w-1.5 bg-neutral-400/40 dark:bg-neutral-600/60")
                }
              ></span>
            </button>
          {/each}
        </div>
      {/if}
      <!-- iOS-style "App Library" trailing-page entry (always present, even with a
           single icon page). A bigger 4×4 mini-app-grid icon, like the iOS App
           Library indicator. Left-swipe past the last page reaches the same place. -->
      <button
        type="button"
        data-testid="app-library-entry"
        aria-label={t("appLibrary.title")}
        title={t("appLibrary.title")}
        onclick={() => home.emit("library")}
        class="ml-1 grid h-6 w-6 cursor-pointer place-items-center rounded-[7px] bg-white/45 shadow-sm ring-1 ring-black/5 transition hover:scale-105 active:scale-90 dark:bg-white/10 dark:ring-white/10"
      >
        <span aria-hidden="true" class="grid w-4 grid-cols-4 gap-px">
          {#each Array(16) as _, i (i)}
            <span class="h-[3px] w-[3px] rounded-[0.5px] bg-neutral-600/70 dark:bg-neutral-300/70"></span>
          {/each}
        </span>
      </button>
    </div>
  </div>

  <!-- bottom dock bar: single fixed row (no paging) -->
  <div
    class="dock-mag flex items-end justify-around rounded-3xl bg-white/30 px-2 py-3 shadow-inner ring-1 ring-black/5 backdrop-blur-md dark:bg-neutral-900/40 dark:ring-white/10"
  >
    {#each dockIds as id (id)}
      {@render tile(id)}
    {/each}
  </div>
</div>


{#snippet tile(id: string)}
  <button
    aria-label={labelOf(id)}
    title={labelOf(id)}
    draggable={reorderable}
    onclick={() => handleTap(id)}
    ondragstart={(e) => {
      handleDragStart(id);
      e.dataTransfer?.setData("text/plain", id);
    }}
    ondragover={(e) => e.preventDefault()}
    ondrop={(e) => {
      e.preventDefault();
      handleDrop(id);
    }}
    class="group flex w-16 flex-col items-center gap-1 outline-none"
  >
    <span class="relative">
      <AppIcon
        id={id}
        icon={iconOf(id)}
        tileClassName={
          "h-14 w-14 rounded-[19px] group-hover:-translate-y-0.5 group-active:scale-90" +
          (pulseId === id ? " animate-pulse ring-2 ring-accent" : "")
        }
        glyphClassName="text-[2.5rem]"
      />
      {#if unreadOf(id) > 0}
        <span
          class="absolute -right-1 -top-1 grid min-w-[18px] place-items-center rounded-full bg-danger px-1 text-[11px] font-bold text-white ring-2 ring-white dark:ring-neutral-900"
        >{unreadOf(id) > 99 ? "99+" : unreadOf(id)}</span>
      {/if}
    </span>
    <span
      class="max-w-full truncate text-xs font-medium text-neutral-800 transition-colors group-hover:text-accent dark:text-neutral-200"
    >{labelOf(id)}</span>
  </button>
{/snippet}
