// crates/amos-tauri/frontend-ts/src/components/NotificationBanner.tsx
import { useEffect, useRef, useState } from "react";
import { writeStoreValue } from "../lib/amosStore";
import { NOTIF_KEY, newestAddedNotif, removeAppNotifs, type Notif } from "../lib/settings";
import { useStoreValue } from "../lib/useStoreValue";
import { useAlertPolicy } from "../lib/sound";

/** How long a banner stays up before auto-dismissing. */
const SHOW_MS = 4200;

/**
 * Transient "notification arrived" banner.
 *
 * Mounted once in the phone frame (over every screen: home / app / lock). When a
 * notification is added and Do-Not-Disturb is OFF, the newest one appears as a
 * toast near the top for a few seconds (tap to dismiss). DND suppresses the
 * banner — those notifications stay only in the Notification Center.
 */
export default function NotificationBanner() {
  const notifs = useStoreValue<Notif[]>(NOTIF_KEY, []);
  const { dnd } = useAlertPolicy();
  const [banner, setBanner] = useState<Notif | null>(null);
  const timer = useRef<number | null>(null);
  const prev = useRef<Notif[]>(notifs);

  const clearTimer = () => {
    if (timer.current !== null) {
      window.clearTimeout(timer.current);
      timer.current = null;
    }
  };

  useEffect(() => {
    // DND hides a visible banner and suppresses new ones.
    if (dnd) {
      setBanner(null);
      clearTimer();
      prev.current = notifs;
      return;
    }
    const added = newestAddedNotif(prev.current, notifs);
    if (added) {
      setBanner(added);
      clearTimer();
      timer.current = window.setTimeout(() => {
        setBanner(null);
        timer.current = null;
      }, SHOW_MS);
    }
    prev.current = notifs;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [notifs, dnd]);

  useEffect(() => clearTimer, []);

  // Acknowledge: mark the banner's app notifications as read (badge clears) and
  // dismiss the toast. Safe regardless of whether the app is navigable.
  const ack = () => {
    if (!banner) return;
    if (banner.app) {
      writeStoreValue(NOTIF_KEY, removeAppNotifs(notifs, banner.app));
    }
    setBanner(null);
  };

  if (!banner) return null;
  return (
    <button
      onClick={ack}
      aria-label="notification: acknowledge"
      className="absolute inset-x-3 top-[46px] z-[70] flex items-start gap-3 rounded-2xl bg-white/90 px-3 py-2.5 text-left shadow-lg ring-1 ring-black/10 backdrop-blur-md dark:bg-neutral-900/90 dark:ring-white/10"
    >
      <span className="text-xl leading-none" aria-hidden>
        {banner.icon ?? "🔔"}
      </span>
      <span className="min-w-0 flex-1">
        <span className="block truncate text-xs font-semibold text-neutral-900 dark:text-white">
          {banner.app ?? banner.title ?? "Notification"}
        </span>
        {banner.title && (
          <span className="block truncate text-xs text-neutral-700 dark:text-neutral-300">
            {banner.title}
          </span>
        )}
        {banner.body && (
          <span className="block truncate text-[11px] text-neutral-500 dark:text-neutral-400">
            {banner.body}
          </span>
        )}
      </span>
      <span aria-hidden className="opacity-50">
        ✓
      </span>
    </button>
  );
}

// crates/amos-tauri/frontend-ts/src/svelte/NotificationBanner.svelte
<script lang="ts">
  // NotificationBanner.svelte — Svelte 5 (runes) port of the React
  // NotificationBanner chrome island. Mounted once in the phone frame, over every
  // screen; when a notification is added and DND is OFF it shows the newest as a
  // toast (tap to acknowledge → clears the app's badge). Pure island: reads the
  // shared NOTIF + DND stores, no external props. Same transient logic + timings.
  import { writeStoreValue } from "../lib/amosStore";
  import {
    NOTIF_KEY,
    SETTINGS_KEY,
    dndActive,
    newestAddedNotif,
    normalizeQuick,
    removeAppNotifs,
    type Notif,
  } from "../lib/settings";
  import { createStoreValue } from "./store";

  const SHOW_MS = 4200;

  const notifStore = createStoreValue<Notif[]>(NOTIF_KEY, []);
  const settingsStore = createStoreValue<unknown>(SETTINGS_KEY, {});

  let notifs = $state<Notif[]>([]);
  let settingsRaw = $state<unknown>({});
  let banner = $state<Notif | null>(null);

  // Transient, non-reactive mirrors of the React refs (prev list + timer id).
  let prev: Notif[] = [];
  let timer: number | null = null;
  // Seed `prev` from the FIRST store read so pre-existing notifications at mount
  // are not mistaken for "just arrived" (mirrors React prev=notifs initialisation).
  let seeded = false;

  $effect(() => {
    const un = notifStore.subscribe((v) => {
      if (!seeded) {
        seeded = true;
        prev = v;
      }
      notifs = v;
    });
    return un;
  });
  $effect(() => {
    const un = settingsStore.subscribe((v) => (settingsRaw = v));
    return un;
  });
  const dnd = $derived(dndActive(normalizeQuick(settingsRaw)));

  const clearTimer = () => {
    if (timer !== null) {
      window.clearTimeout(timer);
      timer = null;
    }
  };

  // React to arrival / DND like the React useEffect([notifs, dnd]).
  $effect(() => {
    clearTimer();
    if (dnd) {
      // DND hides a visible banner and suppresses new ones.
      banner = null;
      prev = notifs;
      return;
    }
    const added = newestAddedNotif(prev, notifs);
    if (added) {
      banner = added;
      timer = window.setTimeout(() => {
        banner = null;
        timer = null;
      }, SHOW_MS);
    }
    prev = notifs;
  });

  // Acknowledge: mark the banner's app notifications as read and dismiss.
  const ack = () => {
    const b = banner;
    if (!b) return;
    if (b.app) {
      writeStoreValue(NOTIF_KEY, removeAppNotifs(notifs, b.app));
    }
    banner = null;
    clearTimer();
  };
</script>

{#if banner}
  <button
    onclick={ack}
    aria-label="notification: acknowledge"
    class="absolute inset-x-3 top-[46px] z-[70] flex items-start gap-3 rounded-2xl bg-white/90 px-3 py-2.5 text-left shadow-lg ring-1 ring-black/10 backdrop-blur-md dark:bg-neutral-900/90 dark:ring-white/10"
  >
    <span class="text-xl leading-none" aria-hidden="true">{banner.icon ?? "🔔"}</span>
    <span class="min-w-0 flex-1">
      <span class="block truncate text-xs font-semibold text-neutral-900 dark:text-white">
        {banner.app ?? banner.title ?? "Notification"}
      </span>
      {#if banner.title}
        <span class="block truncate text-xs text-neutral-700 dark:text-neutral-300">
          {banner.title}
        </span>
      {/if}
      {#if banner.body}
        <span class="block truncate text-[11px] text-neutral-500 dark:text-neutral-400">
          {banner.body}
        </span>
      {/if}
    </span>
    <span aria-hidden="true" class="opacity-50">✓</span>
  </button>
{/if}
