// crates/amos-tauri/frontend-ts/src/components/NotificationCenter.tsx
import { useEffect, useRef, useState } from "react";
import { useI18n } from "../i18n";
import { useTheme } from "../theme";
import { readStoreValue, writeStoreValue } from "../lib/amosStore";
import { useStoreValue } from "../lib/useStoreValue";
import {
  bridged,
  flashlightSet,
  flashlightStatus,
  radioSet,
  radioStatus,
  type FlashlightPayload,
  type RadioPayload,
} from "../lib/backend";
import { useFocusTrap } from "../lib/useFocusTrap";
import {
  FLASHLIGHT_KEY,
  NOTIF_KEY,
  SETTINGS_KEY,
  dndActive,
  flipFlashlight,
  flipLocation,
  flipQuick,
  flipRadio,
  locationEnabled,
  normalizeFlashlight,
  normalizeNotifs,
  normalizeQuick,
  removeNotif,
  seedNotifs,
  type FlashlightStore,
  type Notif,
  type QuickKey,
  type QuickSettings,
  type RadioKey,
} from "../lib/settings";
import { iconSvg, quickIcon } from "../lib/sysIcons";
import { CELLULAR_KEY, normalizeCellular } from "../lib/cellular";
import {
  cellularService,
  cellularStateKey,
  defaultRadioSignal,
  type RadioSignal,
} from "../lib/cellularService";
import { cellularRadio } from "../svelte/cellularRadio";

const QUICK: { key: QuickKey; label: "q.wifi" | "q.bluetooth" | "q.airplane" | "q.dark" | "q.dnd" | "q.location" }[] = [
  { key: "wifi", label: "q.wifi" },
  { key: "bluetooth", label: "q.bluetooth" },
  { key: "airplane", label: "q.airplane" },
  { key: "darkmode", label: "q.dark" },
  { key: "dnd", label: "q.dnd" },
  { key: "location", label: "q.location" },
];

export default function NotificationCenter({
  open,
  onClose,
  onSearch,
  onRecents,
  onEdit,
  onLock,
}: {
  open: boolean;
  onClose: () => void;
  /** Optional "control-center" actions (formerly the home top bar): reachable via
   *  this pull-down shade instead of a cluttered bar on the home page. */
  onSearch?: () => void;
  onRecents?: () => void;
  onEdit?: () => void;
  onLock?: () => void;
}) {
  const { t } = useI18n();
  // The "dark mode" quick tile drives the real theme (not just a cosmetic bit).
  const { dark, toggle: themeToggle } = useTheme();
  const [settings, setSettings] = useState<QuickSettings>(() =>
    normalizeQuick(readStoreValue<unknown>(SETTINGS_KEY, {})),
  );
  const [notifs, setNotifs] = useState<Notif[]>(() => {
    const l = normalizeNotifs(readStoreValue<unknown>(NOTIF_KEY, []));
    if (l.length) return l;
    const s = seedNotifs(Date.now());
    writeStoreValue(NOTIF_KEY, s);
    return s;
  });
  // Torch is read reactively from the shared store so OS-driven changes pushed
  // via `store-updated` (from Rust: the status bar AND an open tile) reflect
  // live, without open-panel polling.
  const flash = normalizeFlashlight(useStoreValue<unknown>(FLASHLIGHT_KEY, {}));
  const rootRef = useRef<HTMLDivElement | null>(null);
  useFocusTrap(open, rootRef, onClose);
  const quiet = dndActive(settings);

  // Controlled cellular: real radio source seam (absent by default → nothing shown,
  // honest/non-misleading; a future on-device modem sets `present` to surface it).
  const cellPrefs = normalizeCellular(useStoreValue<unknown>(CELLULAR_KEY, {}));
  const [radio, setRadio] = useState<RadioSignal>(defaultRadioSignal);
  useEffect(() => {
    const unsub = cellularRadio.subscribe(setRadio);
    return () => unsub();
  }, []);
  const cellStatusKey = cellularStateKey(cellularService(cellPrefs, radio));

  // Merge an authoritative backend snapshot into the local quick-settings,
  // preserving the non-radio toggles (darkmode/dnd/location).
  const mergeRadio = (s: QuickSettings, r: RadioPayload): QuickSettings => ({
    ...s,
    wifi: r.wifi,
    bluetooth: r.bluetooth,
    airplane: r.airplane,
  });

  // Merge an authoritative torch snapshot into the local store mirror.
  const mergeFlash = (p: FlashlightPayload): FlashlightStore => ({
    on: p.on,
    torch_present: p.torch_present,
  });

  // When the panel opens inside Tauri, sync radio + torch tiles from the
  // authoritative backend snapshot (e.g. airplane mode or the torch was toggled
  // from another window). We only touch React state here — durability lives in
  // the shared store.
  useEffect(() => {
    if (!open || !bridged()) return;
    let cancelled = false;
    radioStatus().then((snap) => {
      if (!snap || cancelled) return;
      setSettings((prev) => mergeRadio(prev, snap));
    });
    flashlightStatus().then((snap) => {
      if (!snap || cancelled) return;
      // Mirror the authoritative snapshot into the shared store; the reactive
      // read (flash) adopts it and cross-window surfaces stay consistent.
      writeStoreValue(FLASHLIGHT_KEY, mergeFlash(snap));
    });
    return () => {
      cancelled = true;
    };
  }, [open]);

  if (!open) return null;

  const toggle = async (key: QuickKey) => {
    if (key === "darkmode") {
      // Flip the *actual* theme and keep the quick-setting mirror in sync.
      const nextDark = !dark;
      const next = { ...settings, darkmode: nextDark };
      setSettings(next);
      writeStoreValue(SETTINGS_KEY, next);
      themeToggle();
      return;
    }
    if (key === "wifi" || key === "bluetooth" || key === "airplane") {
      await toggleRadio(key);
      return;
    }
    if (key === "location") {
      // System location-services master: defaults ON; tapping flips it OFF/ON.
      const next = flipLocation(settings);
      setSettings(next);
      writeStoreValue(SETTINGS_KEY, next);
      return;
    }
    const next = flipQuick(settings, key);
    setSettings(next);
    writeStoreValue(SETTINGS_KEY, next);
  };

  // Radio toggles go through the real `radio_*` backend when it is reachable
  // (authoritative snapshot incl. airplane cascade); outside Tauri we fall back
  // to the same policy locally so the UI still behaves identically.
  const toggleRadio = async (key: RadioKey) => {
    // wifi / bluetooth are disabled while airplane mode is on — mirror the
    // backend guard, so a gated tap is a clean no-op rather than an RPC error.
    if (key !== "airplane" && settings.airplane) return;
    const on = !!settings[key];
    if (bridged()) {
      const snap = await radioSet(key, !on);
      if (snap) {
        const merged = mergeRadio(settings, snap);
        setSettings(merged);
        writeStoreValue(SETTINGS_KEY, merged);
        return;
      }
      // Rejected/unavailable (e.g. daemon bridge down): don't keep stale tiles —
      // pull the authoritative state instead.
      const live = await radioStatus();
      if (live) setSettings((prev) => mergeRadio(prev, live));
      return;
    }
    const next = flipRadio(settings, key);
    setSettings(next);
    writeStoreValue(SETTINGS_KEY, next);
  };
  // Torch toggles go through the real `flashlight_*` backend when it is
  // reachable (authoritative snapshot); outside Tauri we fall back to the same
  // local flip so the UI still behaves identically. Durability lives in the
  // dedicated `amos.flashlight` store.
  const toggleFlash = async () => {
    const nextOn = !flash.on;
    if (bridged()) {
      const snap = await flashlightSet(nextOn);
      if (snap) {
        // Write the authoritative snapshot into the shared store; the reactive
        // read (flash) adopts it and cross-window surfaces stay in sync.
        writeStoreValue(FLASHLIGHT_KEY, mergeFlash(snap));
        return;
      }
      // Rejected/unavailable (e.g. no torch hardware): don't keep a stale tile —
      // pull the authoritative state instead.
      const live = await flashlightStatus();
      if (live) writeStoreValue(FLASHLIGHT_KEY, mergeFlash(live));
      return;
    }
    const next = flipFlashlight(flash);
    writeStoreValue(FLASHLIGHT_KEY, next);
  };
  const clear = () => {
    setNotifs([]);
    writeStoreValue(NOTIF_KEY, []);
  };
  const dismiss = (id: string) => {
    const next = removeNotif(notifs, id);
    setNotifs(next);
    writeStoreValue(NOTIF_KEY, next);
  };

  return (
    <div
      ref={rootRef}
      role="dialog"
      aria-modal="true"
      aria-label={t("nc.title")}
      className="drop-in absolute inset-0 z-40 flex flex-col bg-white/45 p-4 backdrop-blur-2xl backdrop-saturate-150 dark:bg-neutral-950/60"
    >
      <div className="flex items-center justify-between px-1">
        <h2 className="text-xl font-semibold tracking-tight">{t("nc.title")}</h2>
        <button
          onClick={onClose}
          className="rounded-full bg-neutral-200/80 px-4 py-1.5 text-sm font-medium text-accent transition active:scale-95 dark:bg-white/10"
        >
          {t("common.done")}
        </button>
      </div>

      {/* Control-center system actions (moved off the home top bar): each closes
          this shade and opens the target surface. */}
      {(() => {
        type Act = { icon: "search" | "recents" | "pencil" | "lock"; label: string; fn?: () => void };
        const acts: Act[] = (
          [
            { icon: "search", label: "search", fn: onSearch },
            { icon: "recents", label: "recents", fn: onRecents },
            { icon: "pencil", label: "edit home", fn: onEdit },
            { icon: "lock", label: "lock", fn: onLock },
          ] as Act[]
        ).filter((a) => a.fn);
        if (!acts.length) return null;
        return (
          <div className="mt-2 flex items-center justify-end gap-2">
            {acts.map((a) => (
              <button
                key={a.label}
                aria-label={a.label}
                title={a.label}
                onClick={() => {
                  a.fn!();
                  onClose();
                }}
                className="grid h-9 w-9 place-items-center rounded-full bg-white/55 text-sm ring-1 ring-white/50 shadow-sm transition active:scale-90 dark:bg-white/10 dark:ring-white/10"
              >
                <span data-icon={a.icon} dangerouslySetInnerHTML={{ __html: iconSvg(a.icon, "h-[17px] w-[17px]") }} />
              </button>
            ))}
          </div>
        );
      })()}

      {/* Torch / flashlight — illumination control (ephemeral hardware state).
          A dedicated full-width tile above the preference quick-settings. */}
      <button
        onClick={toggleFlash}
        aria-pressed={flash.on}
        disabled={!flash.torch_present}
        className={
          "mt-3 flex items-center justify-between rounded-3xl px-4 py-3 text-sm font-semibold transition active:scale-[0.98] disabled:opacity-40 " +
          (flash.on
            ? "bg-amber-400 text-neutral-900 shadow-[0_6px_16px_rgba(245,158,11,0.45)]"
            : "bg-white/55 text-neutral-800 ring-1 ring-white/50 shadow-sm dark:bg-white/10 dark:text-neutral-200 dark:ring-white/10")
        }
      >
        <span className="flex items-center gap-2.5">
          <span data-icon="flashlight" className="text-xl leading-none" dangerouslySetInnerHTML={{ __html: iconSvg("flashlight", "h-[22px] w-[22px]") }} />
          {t("q.flashlight")}
        </span>
        {!flash.torch_present ? (
          <span className="text-xs font-medium opacity-50">{t("nc.torchNone")}</span>
        ) : (
          <span className={"text-xs font-medium " + (flash.on ? "opacity-80" : "opacity-50")}>
            {flash.on ? t("nc.torchOn") : t("nc.torchOff")}
          </span>
        )}
      </button>

      {/* Cellular module — only when a REAL modem source is present (on-device). This
          build has none (radio.present=false) so it stays hidden: honest, never a fake
          phone affordance. Once a real Android signal source is wired it appears here. */}
      {radio.present && (
        <div
          data-testid="nc-cellular"
          className="mt-3 flex items-center justify-between rounded-3xl bg-white/55 px-4 py-3 text-sm font-semibold text-neutral-800 ring-1 ring-white/50 shadow-sm dark:bg-white/10 dark:text-neutral-200 dark:ring-white/10"
        >
          <span className="flex items-center gap-2.5">{t("settings.cellular")}</span>
          <span className="text-xs font-medium opacity-70">{t(cellStatusKey)}</span>
        </div>
      )}

      {/* Quick settings — iOS Control-Center style translucent tiles */}
      <div className="mt-4 grid grid-cols-3 gap-2.5">
        {QUICK.map((q) => {
          const on =
            q.key === "darkmode"
              ? dark
              : q.key === "location"
                ? locationEnabled(settings)
                : !!settings[q.key];
          return (
            <button
              key={q.key}
              onClick={() => toggle(q.key)}
              aria-pressed={on}
              className={
                "flex flex-col items-center justify-center gap-1.5 rounded-3xl py-4 text-[11px] font-medium backdrop-blur transition active:scale-95 " +
                (on
                  ? "bg-accent text-white shadow-[0_6px_16px_rgba(10,132,255,0.35)]"
                  : "bg-white/55 text-neutral-800 ring-1 ring-white/50 shadow-sm dark:bg-white/10 dark:text-neutral-200 dark:ring-white/10")
              }
            >
              <span data-icon={q.key} className="text-xl leading-none" dangerouslySetInnerHTML={{ __html: iconSvg(quickIcon(q.key), "h-[22px] w-[22px]") }} />
              {t(q.label)}
            </button>
          );
        })}
      </div>

      <div className="mt-3 flex items-center justify-between px-1">
        <span className="text-xs font-semibold uppercase tracking-widest opacity-50">
          {quiet ? (
            <span className="inline-flex items-center gap-1 normal-case tracking-normal text-accent">
              <span data-icon="moon" className="grid h-4 w-4 place-items-center" dangerouslySetInnerHTML={{ __html: iconSvg("moon", "h-4 w-4") }} />
              {t("nc.dnd")}
            </span>
          ) : (
            `${notifs.length} ·`
          )}
        </span>
        <button onClick={clear} className="text-xs font-medium text-accent hover:underline">
          {t("nc.clear")}
        </button>
      </div>

      <div className="mt-2 flex-1 space-y-2.5 overflow-auto pr-0.5">
        {notifs.length === 0 ? (
          <p className="py-12 text-center text-sm opacity-50">{t("nc.empty")}</p>
        ) : (
          notifs.map((n) => (
            <div
              key={n.id}
              className={
                "rounded-3xl p-3.5 shadow-sm ring-1 ring-black/5 dark:ring-white/10 " +
                (quiet
                  ? "bg-white/30 opacity-60 saturate-50 dark:bg-white/5"
                  : "bg-white/60 dark:bg-white/10")
              }
            >
              <div className="flex items-center justify-between text-xs">
                <span className="font-semibold">
                  {n.icon} {n.app ?? n.title}
                </span>
                <button
                  onClick={() => dismiss(n.id)}
                  aria-label="dismiss"
                  data-icon="x"
                  className="grid h-6 w-6 place-items-center rounded-full opacity-60 transition hover:opacity-100"
                  dangerouslySetInnerHTML={{ __html: iconSvg("x", "h-3 w-3") }}
                />
              </div>
              {n.title && <div className="mt-1 text-sm font-medium">{n.title}</div>}
              {n.body && <div className="text-xs opacity-70">{n.body}</div>}
            </div>
          ))
        )}
      </div>
    </div>
  );
}

// crates/amos-tauri/frontend-ts/src/svelte/NotificationCenter.svelte
<script lang="ts">
  // NotificationCenter.svelte — Svelte 5 (runes) port of the React control-center
  // sheet. CONTROLLED: the shell owns `open` (over propsBus "nc") and receives
  // shell actions (search/recents/edit/lock). Radio + torch tiles go through the
  // real `radio_*`/`flashlight_*` backend when bridged (authoritative), else fall
  // back to the SAME local policy so offline behaviour matches React. Notifications
  // list is reactive over the shared amos.notifications store.
  import { t } from "./locale.svelte";
  import { themeDark, toggleTheme } from "./theme.svelte";
  import { writeStoreValue } from "../lib/amosStore";
  import {
    bridged,
    flashlightSet,
    flashlightStatus,
    radioSet,
    radioStatus,
    type FlashlightPayload,
    type RadioPayload,
  } from "../lib/backend";
  import { attachFocusTrap } from "../lib/focusTrap";
  import { iconSvg, quickIcon } from "../lib/sysIcons";
  import { propsChannel } from "./propsBus";
  import { createStoreValue } from "./store";
  import { cellularRadio } from "./cellularRadio";
  import { CELLULAR_KEY, defaultCellular, normalizeCellular, type CellularPrefs } from "../lib/cellular";
  import {
    cellularService,
    cellularStateKey,
    defaultRadioSignal,
    type RadioSignal,
  } from "../lib/cellularService";
  import {
    FLASHLIGHT_KEY,
    NOTIF_KEY,
    SETTINGS_KEY,
    dndActive,
    flipFlashlight,
    flipLocation,
    flipQuick,
    flipRadio,
    locationEnabled,
    normalizeFlashlight,
    normalizeNotifs,
    normalizeQuick,
    removeNotif,
    seedNotifs,
    type FlashlightStore,
    type Notif,
    type QuickKey,
    type QuickSettings,
    type RadioKey,
  } from "../lib/settings";

  const QUICK: { key: QuickKey; label: string }[] = [
    { key: "wifi", label: "q.wifi" },
    { key: "bluetooth", label: "q.bluetooth" },
    { key: "airplane", label: "q.airplane" },
    { key: "darkmode", label: "q.dark" },
    { key: "dnd", label: "q.dnd" },
    { key: "location", label: "q.location" },
  ];

  interface NcProps {
    open: boolean;
  }
  const bus = propsChannel<NcProps>("nc");
  let incoming = $state<NcProps | null>(null);
  $effect(() => {
    const un = bus.subscribe((v) => {
      if (v !== undefined) incoming = v;
    });
    return un;
  });
  const open = $derived(incoming?.open ?? false);

  const settingsStore = createStoreValue<unknown>(SETTINGS_KEY, {});
  const notifStore = createStoreValue<Notif[]>(NOTIF_KEY, []);
  const flashStore = createStoreValue<unknown>(FLASHLIGHT_KEY, {});
  let settings = $state<QuickSettings>({});
  let notifs = $state<Notif[]>([]);
  let flash = $state<FlashlightStore>({ on: false, torch_present: true });
  let cellPrefs = $state<CellularPrefs>(defaultCellular());
  let radio = $state<RadioSignal>(defaultRadioSignal());
  const cellularStore = createStoreValue<unknown>(CELLULAR_KEY, {});
  $effect(() => {
    const un = settingsStore.subscribe((v) => (settings = normalizeQuick(v)));
    return un;
  });
  $effect(() => {
    const un = notifStore.subscribe((v) => (notifs = normalizeNotifs(v)));
    return un;
  });
  $effect(() => {
    const un = flashStore.subscribe((v) => (flash = normalizeFlashlight(v)));
    return un;
  });
  $effect(() => {
    const un = cellularStore.subscribe((v) => (cellPrefs = normalizeCellular(v)));
    return un;
  });
  $effect(() => {
    const un = cellularRadio.subscribe((v) => (radio = v));
    return un;
  });

  // Seed demo notifications once when the store is empty (mirrors React's mount
  // seed). A later manual clear reaches the true empty state.
  let seeded = false;
  $effect(() => {
    if (!seeded && notifs.length === 0) {
      seeded = true;
      writeStoreValue(NOTIF_KEY, seedNotifs(Date.now()));
    }
  });

  const dark = $derived(themeDark());
  const quiet = $derived(dndActive(settings));
  // Controlled cellular: only meaningful once a REAL radio is present (on-device).
  // No modem → radio.present false → nothing is shown (honest, not misleading).
  const cellStatusKey = $derived(cellularStateKey(cellularService(cellPrefs, radio)));
  let rootEl: HTMLDivElement | undefined = $state();
  $effect(() => {
    if (!open || !rootEl) return;
    return attachFocusTrap(rootEl, close);
  });

  const mergeRadio = (s: QuickSettings, r: RadioPayload): QuickSettings => ({
    ...s,
    wifi: r.wifi,
    bluetooth: r.bluetooth,
    airplane: r.airplane,
  });
  const mergeFlash = (p: FlashlightPayload): FlashlightStore => ({
    on: p.on,
    torch_present: p.torch_present,
  });
  const persistSettings = (next: QuickSettings) => writeStoreValue(SETTINGS_KEY, next);

  const toggle = async (key: QuickKey) => {
    if (key === "darkmode") {
      const nextDark = !dark;
      persistSettings({ ...settings, darkmode: nextDark });
      toggleTheme();
      return;
    }
    if (key === "wifi" || key === "bluetooth" || key === "airplane") {
      await toggleRadio(key);
      return;
    }
    if (key === "location") {
      persistSettings(flipLocation(settings)); // defaults ON; tap flips OFF/ON
      return;
    }
    persistSettings(flipQuick(settings, key));
  };

  // Radio tiles go through the real backend when bridged; otherwise the same
  // local policy (incl. airplane cascade) so offline behaves identically.
  const toggleRadio = async (key: RadioKey) => {
    if (key !== "airplane" && settings.airplane) return; // gated no-op under APM
    const on = !!settings[key];
    if (bridged()) {
      const snap = await radioSet(key, !on);
      if (snap) {
        persistSettings(mergeRadio(settings, snap));
        return;
      }
      const live = await radioStatus();
      if (live) settings = mergeRadio(settings, live);
      return;
    }
    persistSettings(flipRadio(settings, key));
  };

  const toggleFlash = async () => {
    if (bridged()) {
      const snap = await flashlightSet(!flash.on);
      if (snap) {
        writeStoreValue(FLASHLIGHT_KEY, mergeFlash(snap));
        return;
      }
      const live = await flashlightStatus();
      if (live) writeStoreValue(FLASHLIGHT_KEY, mergeFlash(live));
      return;
    }
    writeStoreValue(FLASHLIGHT_KEY, flipFlashlight(flash));
  };

  const clear = () => writeStoreValue(NOTIF_KEY, []);
  const dismiss = (id: string) => writeStoreValue(NOTIF_KEY, removeNotif(notifs, id));

  const close = () => bus.emit("close");
  const act = (name: string) => {
    bus.emit(name); // search / recents / edit / lock
    bus.emit("close");
  };

</script>

{#if open}
  <div
    bind:this={rootEl}
    role="dialog"
    aria-modal="true"
    aria-label={t("nc.title")}
    class="drop-in absolute inset-0 z-40 flex flex-col bg-white/45 p-4 backdrop-blur-2xl backdrop-saturate-150 dark:bg-neutral-950/60"
  >
    <div class="flex items-center justify-between px-1">
      <h2 class="text-xl font-semibold tracking-tight">{t("nc.title")}</h2>
      <button
        onclick={close}
        class="rounded-full bg-neutral-200/80 px-4 py-1.5 text-sm font-medium text-accent transition active:scale-95 dark:bg-white/10"
      >{t("common.done")}</button>
    </div>

    <!-- Control-center system actions (formerly the home top bar). -->
    <div class="mt-2 flex items-center justify-end gap-2">
      <button aria-label="search" title="search" onclick={() => act("search")} class="grid h-9 w-9 place-items-center rounded-full bg-white/55 text-sm ring-1 ring-white/50 shadow-sm transition active:scale-90 dark:bg-white/10 dark:ring-white/10"><span data-icon="search">{@html iconSvg("search", "h-[17px] w-[17px]")}</span></button>
      <button aria-label="recents" title="recents" onclick={() => act("recents")} class="grid h-9 w-9 place-items-center rounded-full bg-white/55 text-sm ring-1 ring-white/50 shadow-sm transition active:scale-90 dark:bg-white/10 dark:ring-white/10"><span data-icon="recents">{@html iconSvg("recents", "h-[17px] w-[17px]")}</span></button>
      <button aria-label="edit home" title="edit home" onclick={() => act("edit")} class="grid h-9 w-9 place-items-center rounded-full bg-white/55 text-sm ring-1 ring-white/50 shadow-sm transition active:scale-90 dark:bg-white/10 dark:ring-white/10"><span data-icon="pencil">{@html iconSvg("pencil", "h-[17px] w-[17px]")}</span></button>
      <button aria-label="lock" title="lock" onclick={() => act("lock")} class="grid h-9 w-9 place-items-center rounded-full bg-white/55 text-sm ring-1 ring-white/50 shadow-sm transition active:scale-90 dark:bg-white/10 dark:ring-white/10"><span data-icon="lock">{@html iconSvg("lock", "h-[17px] w-[17px]")}</span></button>
    </div>

    <!-- Torch / flashlight tile. -->
    <button
      onclick={() => void toggleFlash()}
      aria-pressed={flash.on}
      disabled={!flash.torch_present}
      class={
        "mt-3 flex items-center justify-between rounded-3xl px-4 py-3 text-sm font-semibold transition active:scale-[0.98] disabled:opacity-40 " +
        (flash.on
          ? "bg-amber-400 text-neutral-900 shadow-[0_6px_16px_rgba(245,158,11,0.45)]"
          : "bg-white/55 text-neutral-800 ring-1 ring-white/50 shadow-sm dark:bg-white/10 dark:text-neutral-200 dark:ring-white/10")
      }
    >
      <span class="flex items-center gap-2.5">
        <span data-icon="flashlight" class="text-xl leading-none">{@html iconSvg("flashlight", "h-[22px] w-[22px]")}</span>
        {t("q.flashlight")}
      </span>
      {#if !flash.torch_present}
        <span class="text-xs font-medium opacity-50">{t("nc.torchNone")}</span>
      {:else}
        <span class={"text-xs font-medium " + (flash.on ? "opacity-80" : "opacity-50")}>
          {flash.on ? t("nc.torchOn") : t("nc.torchOff")}
        </span>
      {/if}
    </button>

    <!-- Cellular module — only when a REAL modem source is present. This build has
         none (radio.present=false) so it stays hidden: honest, never a fake phone
         affordance. Once a real Android signal source is wired it appears here. -->
    {#if radio.present}
      <div
        class="mt-3 flex items-center justify-between rounded-3xl bg-white/55 px-4 py-3 text-sm font-semibold text-neutral-800 ring-1 ring-white/50 shadow-sm dark:bg-white/10 dark:text-neutral-200 dark:ring-white/10"
        data-testid="nc-cellular"
      >
        <span class="flex items-center gap-2.5">{t("settings.cellular")}</span>
        <span class="text-xs font-medium opacity-70">{t(cellStatusKey)}</span>
      </div>
    {/if}

    <!-- Quick settings tiles. -->
    <div class="mt-4 grid grid-cols-3 gap-2.5">
      {#each QUICK as q (q.key)}
        {@const on = q.key === "darkmode" ? dark : q.key === "location" ? locationEnabled(settings) : !!settings[q.key]}
        <button
          onclick={() => void toggle(q.key)}
          aria-pressed={on}
          class={
            "flex flex-col items-center justify-center gap-1.5 rounded-3xl py-4 text-[11px] font-medium backdrop-blur transition active:scale-95 " +
            (on
              ? "bg-accent text-white shadow-[0_6px_16px_rgba(10,132,255,0.35)]"
              : "bg-white/55 text-neutral-800 ring-1 ring-white/50 shadow-sm dark:bg-white/10 dark:text-neutral-200 dark:ring-white/10")
          }
        >
          <span data-icon={q.key} class="text-xl leading-none">{@html iconSvg(quickIcon(q.key), "h-[22px] w-[22px]")}</span>
          {t(q.label)}
        </button>
      {/each}
    </div>

    <div class="mt-3 flex items-center justify-between px-1">
      <span class="text-xs font-semibold uppercase tracking-widest opacity-50">
        {#if quiet}
          <span class="inline-flex items-center gap-1 normal-case tracking-normal text-accent">
            <span data-icon="moon" class="grid h-4 w-4 place-items-center">{@html iconSvg("moon", "h-4 w-4")}</span>
            {t("nc.dnd")}
          </span>
        {:else}
          {notifs.length} ·
        {/if}
      </span>
      <button onclick={clear} aria-label="clear" class="text-xs font-medium text-accent hover:underline">{t("nc.clear")}</button>
    </div>

    <div class="mt-2 flex-1 space-y-2.5 overflow-auto pr-0.5">
      {#if notifs.length === 0}
        <p class="py-12 text-center text-sm opacity-50">{t("nc.empty")}</p>
      {:else}
        {#each notifs as n (n.id)}
          <div
            class={
              "rounded-3xl p-3.5 shadow-sm ring-1 ring-black/5 dark:ring-white/10 " +
              (quiet ? "bg-white/30 opacity-60 saturate-50 dark:bg-white/5" : "bg-white/60 dark:bg-white/10")
            }
          >
            <div class="flex items-center justify-between text-xs">
              <span class="font-semibold">{n.icon} {n.app ?? n.title}</span>
              <button
                onclick={() => dismiss(n.id)}
                aria-label="dismiss"
                data-icon="x"
                class="grid h-6 w-6 place-items-center rounded-full opacity-60 transition hover:opacity-100"
              >{@html iconSvg("x", "h-3 w-3")}</button>
            </div>
            {#if n.title}<div class="mt-1 text-sm font-medium">{n.title}</div>{/if}
            {#if n.body}<div class="text-xs opacity-70">{n.body}</div>{/if}
          </div>
        {/each}
      {/if}
    </div>
  </div>
{/if}
