// crates/amos-tauri/frontend-ts/src/components/StatusBar.tsx
import { useEffect, useState } from "react";
import { batteryPercent, fmtClock } from "../lib/time";
import { SETTINGS_KEY, FLASHLIGHT_KEY, applyConnectivity, normalizeFlashlight, normalizeQuick, radioIcons, torchOn } from "../lib/settings";
import { useStoreValue } from "../lib/useStoreValue";
import { useOnline } from "../lib/useOnline";
import { useAlertPolicy } from "../lib/sound";
import { batterySvg, iconSvg, radioIcon, type SysIconName } from "../lib/sysIcons";

export default function StatusBar() {
  const [now, setNow] = useState(() => new Date());
  const settings = useStoreValue<unknown>(SETTINGS_KEY, {});
  const flashStore = useStoreValue<unknown>(FLASHLIGHT_KEY, {});
  const online = useOnline();
  const quick = normalizeQuick(settings);
  const flashOn = torchOn(normalizeFlashlight(flashStore));
  // Wi-Fi reads as "on" only when enabled AND the host is actually online.
  const icons = applyConnectivity(radioIcons(quick), online);
  const { dnd, effective } = useAlertPolicy();
  // Persistent alert indicators: moon while Do-Not-Disturb; otherwise a muted
  // bell when the ring/vibrate policy mutes alerts. Nothing extra by default.
  const alertIcon: SysIconName | null = dnd
    ? "moon"
    : effective.ring || effective.vibrate
      ? null
      : "mutedBell";
  const battery = batteryPercent(now);

  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(id);
  }, []);
  return (
    <div className="relative flex items-center justify-between px-4 pb-1 pt-3 text-xs font-semibold">
      <span className="tabular-nums">{fmtClock(now)}</span>
      {/* Dynamic Island */}
      <span
        aria-hidden
        className="pointer-events-none absolute left-1/2 top-[9px] h-[22px] w-[112px] -translate-x-1/2 rounded-full bg-black shadow-sm"
      />
      <span className="flex items-center gap-1 text-[10px] opacity-80" aria-label="network status">
        {alertIcon && (
          <span
            data-icon={alertIcon}
            aria-label={dnd ? "do not disturb" : "alerts muted"}
            title={dnd ? "Do Not Disturb" : "alerts muted"}
            dangerouslySetInnerHTML={{ __html: iconSvg(alertIcon) }}
          />
        )}
        {flashOn && (
          <span
            data-icon="flashlight"
            aria-label="flashlight on"
            title="Flashlight"
            dangerouslySetInnerHTML={{ __html: iconSvg("flashlight") }}
          />
        )}
        {icons.map((ic) => (
          <span
            key={ic.kind}
            data-icon={ic.kind}
            className={ic.on ? "" : "opacity-40"}
            title={ic.kind === "wifi" && !online ? "wifi: no connection" : undefined}
            dangerouslySetInnerHTML={{ __html: iconSvg(radioIcon(ic.kind)) }}
          />
        ))}
        <span className="flex items-center gap-1 tabular-nums" aria-label="battery level">
          <span aria-hidden dangerouslySetInnerHTML={{ __html: batterySvg(battery) }} />
          <span aria-hidden>{battery}%</span>
        </span>
      </span>
    </div>
  );
}

// crates/amos-tauri/frontend-ts/src/svelte/StatusBar.svelte
<script lang="ts">
  // StatusBar.svelte — Svelte 5 (runes) port of the React `StatusBar` shell
  // chrome. It is a pure "island": no external props/events — it reads the SAME
  // shared stores (quick settings / flashlight / sound) and live time/online that
  // the React StatusBar reads, so it can be hosted by the React shell with the
  // generic SvelteAppHost (className="") and must never drift from the original.
  import { fmtClock, batteryPercent } from "../lib/time";
  import {
    SETTINGS_KEY,
    FLASHLIGHT_KEY,
    applyConnectivity,
    normalizeFlashlight,
    normalizeQuick,
    radioIcons,
    torchOn,
  } from "../lib/settings";
  import { SOUND_KEY, normalizeSound, effectiveAlert } from "../lib/sound";
  import { createStoreValue } from "./store";
  import { batterySvg, iconSvg, radioIcon } from "../lib/sysIcons";

  const settingsStore = createStoreValue<unknown>(SETTINGS_KEY, {});
  const flashStore = createStoreValue<unknown>(FLASHLIGHT_KEY, {});
  const soundStore = createStoreValue<unknown>(SOUND_KEY, {});
  let settingsRaw = $state<unknown>({});
  let flashRaw = $state<unknown>({});
  let soundRaw = $state<unknown>({});
  let now = $state(new Date());
  let online = $state(typeof navigator !== "undefined" ? navigator.onLine : true);

  $effect(() => {
    const un = settingsStore.subscribe((v) => (settingsRaw = v));
    return un;
  });
  $effect(() => {
    const un = flashStore.subscribe((v) => (flashRaw = v));
    return un;
  });
  $effect(() => {
    const un = soundStore.subscribe((v) => (soundRaw = v));
    return un;
  });
  $effect(() => {
    const id = setInterval(() => (now = new Date()), 1000);
    return () => clearInterval(id);
  });
  $effect(() => {
    const on = () => (online = true);
    const off = () => (online = false);
    window.addEventListener("online", on);
    window.addEventListener("offline", off);
    return () => {
      window.removeEventListener("online", on);
      window.removeEventListener("offline", off);
    };
  });

  const quick = $derived(normalizeQuick(settingsRaw));
  const flashOn = $derived(torchOn(normalizeFlashlight(flashRaw)));
  // Wi-Fi reads as "on" only when enabled AND the host is actually online.
  const icons = $derived(applyConnectivity(radioIcons(quick), online));
  const dnd = $derived(!!quick.dnd);
  const effective = $derived(effectiveAlert(normalizeSound(soundRaw), dnd));
  // Persistent alert indicators: moon while Do-Not-Disturb; else a muted bell
  // when the ring/vibrate policy mutes alerts. Nothing extra in the default state.
  const alertIcon = $derived(
    dnd ? ("moon" as const) : effective.ring || effective.vibrate ? null : ("mutedBell" as const),
  );
</script>

<div class="relative flex items-center justify-between px-4 pb-1 pt-3 text-xs font-semibold">
  <span class="tabular-nums">{fmtClock(now)}</span>
  <!-- Dynamic Island -->
  <span
    aria-hidden="true"
    class="pointer-events-none absolute left-1/2 top-[9px] h-[22px] w-[112px] -translate-x-1/2 rounded-full bg-black shadow-sm"
  ></span>
  <span class="flex items-center gap-1 text-[10px] opacity-80" aria-label="network status">
    {#if alertIcon}
      <span
        data-icon={alertIcon}
        aria-label={dnd ? "do not disturb" : "alerts muted"}
        title={dnd ? "Do Not Disturb" : "alerts muted"}
      >{@html iconSvg(alertIcon)}</span>
    {/if}
    {#if flashOn}
      <span data-icon="flashlight" aria-label="flashlight on" title="Flashlight">{@html iconSvg("flashlight")}</span>
    {/if}
    {#each icons as ic (ic.kind)}
      <span
        data-icon={ic.kind}
        class={ic.on ? "" : "opacity-40"}
        title={ic.kind === "wifi" && !online ? "wifi: no connection" : undefined}
      >{@html iconSvg(radioIcon(ic.kind))}</span>
    {/each}
    <span class="flex items-center gap-1 tabular-nums" aria-label="battery level">
      {@html batterySvg(batteryPercent(now))}
      <span aria-hidden="true">{batteryPercent(now)}%</span>
    </span>
  </span>
</div>
